import React, { useState, useEffect } from "react";
import { View, Text, Button, Image, StyleSheet, SafeAreaView } from "react-native";


//  50 CARTE COMPLETE (Scuola)

const carte=[
  {id:1, nome: "Dimentichi il quaderno di italiano", immagine: "fda67c50-652d-4b3e-9588-f78d3e689c2d.png", indice: 5.0},
  {id:2, nome: "Cade l'astuccio aperto per terra e finisce tutto a terra", immagine: "c3915113-4ff0-4c6d-829e-4f11875fb337.png", indice: 7.0},
  {id:3, nome: "Ti dimentichi dello zaino sull’autobus", immagine: "https://thumbs.dreamstime.com/b/una-borsa-perduta-o-uno-zaino-sdraiato-sul-sedile-dell-autobus-sullo-sfondo-sfuocato-del-bus-beni-immobili-nei-trasporti-pubblici-229783651.jpg", indice: 9.0},
  {id:4, nome: "La tua presentazione PowerPoint non si apre", immagine: "https://images.wondershare.com/recoverit/article/2019/05/ppt-error-1.jpg", indice: 11.0},
  {id:5, nome: "Dimentichi che c’è educazione fisica e sei l’unico senza cambio", immagine: "23bf8e1f-0834-45c4-b463-23a465e3c0e1.png", indice: 13.0 },
  {id:6, nome: "Il distributore automatico ti mangia i soldi e resta bloccato", immagine: "https://c8.alamy.com/compit/f1xewt/il-cibo-bloccato-nel-distributore-f1xewt.jpg", indice: 15.0 },
  {id:7, nome: "Ti rubano lo zaino con dentro computer, chiavi e compiti", immagine: "", indice: 17.0 },
  {id:8, nome: "Ti ammali proprio durante la settimana delle verifiche decisive", immagine: "https://www.issalute.it/images/foto_contributi/240x240/raffreddore.jpg", indice: 19.0 },
  {id:9, nome: "Entri nell’aula sbagliata davanti a tutti.", immagine: "c3953c35-96d1-44c6-8059-c54b54435c02.png", indice: 21.0 },
  {id:10, nome: "Il professore ti scopre mentre copi i compiti all’ultimo secondo", immagine: "6c9f8230-59c7-4b4a-9a5c-e7ed4526e393.png", indice: 23.0 },
  {id:11, nome: "Vieni interrogato proprio sull’unico argomento che non hai studiato", immagine: "", indice: 25.0 },
  {id:12, nome: "Rompi accidentalmente la sedia mentre ti siedi", immagine: "435c189f-1271-491b-a2c1-329fdafdacb3.png", indice: 27.0 },
  {id:13, nome: "Suona il telefono in classe nel silenzio totale", immagine: "", indice: 29.0 },
  {id:14, nome: "Ti rendi conto di aver studiato il capitolo sbagliato", immagine: "", indice: 31.0 },
  {id:15, nome: "Il compagno accanto a te vomita durante la verifica", immagine: "", indice: 33.0 },
  {id:16, nome: "Ti si strappano i pantaloni mentre ti alzi", immagine: "", indice: 35.0 },
  {id:17, nome: "Il professore legge ad alta voce un tuo messaggio imbarazzante trovato sul banco", immagine: "", indice: 37.0 },
  {id:18, nome: "Prendi un’insufficienza enorme proprio nel giorno dei colloqui", immagine: "", indice: 39.0 },
  {id:19, nome: "La classe ride per una risposta completamente sbagliata che hai dato", immagine: "", indice: 41.0 },
  {id:20, nome: "Durante l’interrogazione ti viene un vuoto totale", immagine: "", indice: 43.0 },
  {id:21, nome: "Ti rompi gli occhiali durante educazione fisica", immagine: "", indice: 45.0 },
  {id:22, nome: "Rimani chiuso nel bagno durante la ricreazione", immagine: "", indice: 47.0 },
  {id:23, nome: "Il computer del laboratorio si blocca e perdi un progetto fatto in settimane", immagine: "", indice: 49.0 },
  {id:24, nome: "Ti cancellano per errore il voto migliore dal registro", immagine: "", indice: 51.0 },
  {id:25, nome: "Prendi un’insufficienza proprio nel giorno dei colloqui", immagine: "", indice: 53.0 },
  {id:26, nome: "Scopri di avere due verifiche a sorpresa nella stessa mattina", immagine: "", indice: 55.0 },
  {id:27, nome: "Il professore perde il tuo compito migliore e ti mette insufficiente perché “non risulta consegnato”", immagine: "", indice: 57.0 },
  {id:28, nome: "Informatica interroga a sorpresa sull'argomento che non hai capito", immagine: "", indice: 59.0 },
  {id:29, nome: "", immagine: "", indice: 61.0 },
  {id:30, nome: "", immagine: "", indice: 63.0 },
  {id:31, nome: "", immagine: "", indice: 65.0 },
  {id:32, nome: "", immagine: "", indice: 67.0 },
  {id:33, nome: "", immagine: "", indice: 69.0 },
  {id:34, nome: "", immagine: "", indice: 71.0 },
  {id:35, nome: "", immagine: "", indice: 73.0 },
  {id:36, nome: "", immagine: "", indice: 75.0 },
  {id:37, nome: "", immagine: "", indice: 77.0 },
  {id:38, nome: "", immagine: "", indice: 79.0 },
  {id:39, nome: "", immagine: "", indice: 81.0 },
  {id:40, nome: "", immagine: "", indice: 83.0 },
  {id:41, nome: "", immagine: "", indice: 85.0 },
  {id:42, nome: "", immagine: "", indice: 87.0 },
  {id:43, nome: "", immagine: "", indice: 89.0 },
  {id:44, nome: "", immagine: "", indice: 91.0 },
  {id:45, nome: "", immagine: "", indice: 93.0 },
  {id:46, nome: "", immagine: "", indice: 95.0 },
  {id:47, nome: "", immagine: "", indice: 96.0 },
  {id:48, nome: "", immagine: "", indice: 97.0 },
  {id:49, nome: "", immagine: "", indice: 98.0 },
  {id:50, nome: "Fai scena muta all’esame orale davanti alla commissione", immagine: "", indice: 99.5 },
];


